In [1]:
import numpy as np
a = np.array([1, 2, 3])
np.sum(a)

6

In [2]:
a = np.array([1, 2, 3])
a.sum()

6

In [3]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [4]:
a = np.array([1, 2, 3], dtype=np.int16)
a

array([1, 2, 3], dtype=int16)

In [5]:
c1 = np.array([1, 2, 3, 4, 5, 6])
c1

array([1, 2, 3, 4, 5, 6])

In [6]:
c2 = c1.reshape((2, 3))
c2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c3 = c1.reshape((2, 4))
c3

ValueError: cannot reshape array of size 6 into shape (2,4)

In [8]:
c4 = c2.ravel()
c4

array([1, 2, 3, 4, 5, 6])

In [9]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [10]:
np.random.seed(123)
np.random.randint(1, 10, (3, 5))

array([[3, 3, 7, 2, 4],
       [7, 2, 1, 2, 1],
       [1, 4, 5, 1, 1]])